### ISSUE TITLE
Things you've written here are not middlewares, why it is in middleware folder?

### ISSUE THREAD

**Issue by MihailMartinovich** [Julia-Protasevich/library-backend#13]
https://github.com/Julia-Protasevich/library-backend/blob/551c9e8639e321c52fcdf4f86b1fd021324abb3d/middleware/passport.js#L1

**Comment by Julia-Protasevich** [comment]
I'd like to rename the folder to 'authentication' after previous issues are solved to avoid merge conflict hell
